/**
 * The 90-day Chartix technical-analysis series.
 * Day numbers here match the Instagram / LinkedIn posting schedule.
 */
export const CONTENT_PLAN: Record<number, string> = {
  1: 'What is Technical Analysis?',
  2: 'Price Discounts Everything',
  3: 'Why Charts Work',
  4: 'Types of Charts (Line, Bar, Candlestick)',
  5: 'Timeframes Explained',
  6: 'Support vs Resistance',
  7: 'Trend Explained',
  8: 'Dow Theory',
  9: 'Primary vs Secondary Trend',
  10: 'Higher Highs & Higher Lows',
  11: 'Lower Highs & Lower Lows',
  12: 'Trendlines',
  13: 'Channels',
  14: 'Breakout vs Breakdown',
  15: 'Volume Basics',
  16: 'Why Volume Matters',
  17: 'Volume Confirmation',
  18: 'Volume Divergence',
  19: 'Gap Types',
  20: 'Open Interest Basics',
  21: 'Price + Volume Relationship',
  22: 'Moving Average',
  23: 'SMA vs EMA',
  24: 'Golden Cross',
  25: 'Death Cross',
  26: 'VWAP',
  27: 'Anchored VWAP',
  28: 'Common Moving Average Mistakes',
  29: 'Fibonacci Basics',
  30: 'Retracement vs Extension',
  31: 'RSI Basics',
  32: 'RSI Overbought',
  33: 'RSI Oversold',
  34: 'RSI Divergence',
  35: 'Hidden Divergence',
  36: 'RSI Failure Swing',
  37: 'RSI Range Shift',
  38: 'MACD Basics',
  39: 'MACD Crossovers',
  40: 'MACD Histogram',
  41: 'MACD Divergence',
  42: 'Zero Line',
  43: 'Best MACD Settings',
  44: 'MACD Mistakes',
  45: 'ADX',
  46: 'DMI',
  47: 'ATR',
  48: 'Bollinger Bands',
  49: 'Band Squeeze',
  50: 'Mean Reversion',
  51: 'Volatility Explained',
  52: 'Stochastic Oscillator',
  53: 'Williams %R',
  54: 'CCI',
  55: 'ROC',
  56: 'Momentum Indicator',
  57: 'Money Flow Index',
  58: 'OBV',
  59: 'Chaikin Money Flow',
  60: 'Force Index',
  61: 'Doji',
  62: 'Hammer',
  63: 'Hanging Man',
  64: 'Shooting Star',
  65: 'Inverted Hammer',
  66: 'Engulfing Pattern',
  67: 'Morning & Evening Star',
  68: 'Double Top',
  69: 'Double Bottom',
  70: 'Head & Shoulders',
  71: 'Inverse Head & Shoulders',
  72: 'Triangle Pattern',
  73: 'Rectangle Pattern',
  74: 'Flag & Pennant',
  75: 'Cup & Handle',
  76: 'Wedge Pattern',
  77: 'Broadening Pattern',
  78: 'Rounding Bottom',
  79: 'Measured Move',
  80: 'Throwback',
  81: 'Pullback',
  82: 'Risk Reward Ratio',
  83: 'Position Sizing',
  84: 'Stop Loss Placement',
  85: 'Trailing Stop',
  86: 'Expectancy',
  87: 'Win Rate Myth',
  88: 'Compounding',
  89: 'Trading Psychology',
  90: 'Biggest Trading Mistakes Beginners Make',
};

export const TOTAL_DAYS = 90;
