-- FII/DII cash segment daily log
CREATE TABLE IF NOT EXISTS "FiiDiiLog" (
  "date"      TEXT             NOT NULL PRIMARY KEY,  -- YYYY-MM-DD
  "fiiBuy"    DOUBLE PRECISION NOT NULL,
  "fiiSell"   DOUBLE PRECISION NOT NULL,
  "fiiNet"    DOUBLE PRECISION NOT NULL,
  "diiBuy"    DOUBLE PRECISION NOT NULL,
  "diiSell"   DOUBLE PRECISION NOT NULL,
  "diiNet"    DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "FiiDiiLog_date_idx" ON "FiiDiiLog" ("date");

-- F&O participant open interest daily log
CREATE TABLE IF NOT EXISTS "FnoLog" (
  "date"            TEXT             NOT NULL PRIMARY KEY,  -- DD-Mon-YYYY
  "fiiIdxFutLong"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "fiiIdxFutShort"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "fiiStkFutLong"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "fiiStkFutShort"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "fiiIdxCallLong"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "fiiIdxCallShort" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "fiiIdxPutLong"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "fiiIdxPutShort"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiIdxFutLong"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiIdxFutShort"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiStkFutLong"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiStkFutShort"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiIdxCallLong"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiIdxCallShort" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiIdxPutLong"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "diiIdxPutShort"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "createdAt"       TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  "updatedAt"       TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "FnoLog_date_idx" ON "FnoLog" ("date");
